### PR TITLE
[MRG] Submission for JOSS

### PR DESCRIPTION
**Pull request by glouppe**
* [x] Add paper.md
* [x] Add paper.bib
* [x] Bump version (I'll tag a new version after this PR is merged)
* [ ] Fill in submission form at http://joss.theoj.org/papers/new (once this is merged)
* [ ] Anything else I am missing? CC: @cranmer @arfon @jakevdp

@jgpavez Is 0000-0002-7205-0053 your ORCID?

### CODE REVIEW

**Comment by arfon** [comment]
Paper etc. looks great! 👌

**Comment by cranmer** [comment]
I can confirm that is @jgpavez ORCID.

The reference part of the `paper.md` should be empty? That's how it is in the fidget example. Looks good to me.

**Comment by glouppe** [comment]
Thanks! I'll go ahead then.

**Comment by glouppe** [comment]
Submitted at http://joss.theoj.org/papers/26a9ffd9e7b98b1911d89d2ceb268f37

**Comment by cranmer** [comment]
great! Where does the message `The `paper.md` file is in the root directory.` come from? is that from filling out the form?
http://joss.theoj.org/papers

**Comment by glouppe** [comment]
Yes, that input field was supposed to contain extra information such as the location of these files. (Not sure why for the two other papers this input was filled with something which looks like a summary/abstract)

**Comment by arfon** [comment]
> Yes, that input field was supposed to contain extra information such as the location of these files. (Not sure why for the two other papers this input was filled with something which looks like a summary/abstract)

Yeah, I changed the guidelines rather late on... @cranmer @glouppe if you have suggestions for reviewers please add them to https://github.com/openjournals/joss-reviews/issues/11

**Pull request merged**
